apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: react-admin
          image: us-central1-docker.pkg.dev/sonic-shuttle-381413/react-admin/admin:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: admin-dotenv
