apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: php-nginx
spec:
  selector:
    matchLabels:
      app: php-nginx
  template:
    metadata:
      labels:
        app: php-nginx
    spec:
      containers:
        - name: php
          image: us-central1-docker.pkg.dev/sonic-shuttle-381413/symfony/symfony-cicd:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp -r /var/www/symfony/public/. /public &&
                    php /var/www/symfony/bin/console lexik:jwt:generate-keypair --skip-if-exists &&
                    cp -r /var/www/symfony/config/jwt/. /jwt &&
                    php /var/www/symfony/bin/console doctrine:migrations:migrate -n &&
          envFrom:
            - configMapRef:
                name: dot-env
            - secretRef:
                name: app-creds
          volumeMounts:
            - name: public-dir
              mountPath: /public
            - name: jwt-dir
              mountPath: /var/www/symfony/config/jwt
        - name: nginx
          image: nginx:1.16-alpine
          volumeMounts:
            - name: public-dir
              mountPath: /var/www/symfony/public
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: public-dir
          emptyDir: {}
        - name: jwt-dir
          emptyDir: { }
        - name: nginx-conf
          configMap:
            name: nginx-conf
