apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - image: mariadb:10.7.8-focal
      name: mariadb
      env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: MARIADB_DATABASE
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-creds
              key: MARIADB_PASSWORD
      volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  # todo persistence volume
  volumes:
    - name: data
      emptyDir: {}
