apiVersion: v1
kind: Secret
metadata:
  name: database-creds
data:
  MARIADB_ROOT_PASSWORD: cm9vdA==
  MARIADB_DATABASE: c3ltZm9ueQ==
  MARIADB_USER: c3ltZm9ueV91c2Vy
  MARIADB_PASSWORD: c3ltZm9ueV9wYXNz
