apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: app-dev
spec:
  selector:
    app: php-nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: php-nginx
