apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim
spec:
  storageClassName: manual # or StorageClass name if dynamique provisionning (kubectl get sc)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi