#https://source.developers.google.com/p/gcp-devops-338510/r/repo-5

steps:
  - id: 'Clone project'
    name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/yosrib/symfony-ci-cd']

  - id: 'Build docker image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}:${_VERSION}', '.']

  - id: 'Push docker image to registry'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}:${_VERSION}']

  - id: 'Deploy image with kubernetes'
    name: 'gcr.io/cloud-builders/kubectl'
    args :
      - 'set'
      - 'image'
      - 'deployment/app'
      - 'init-service=${_IMAGE}:${_VERSION}'
      - 'php=${_IMAGE}:${_VERSION}'
      - '-n app-dev'
    env :
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=symfony-ci-cd-gke-cluster' # CLUSTER_NAME

substitutions:
  _PROJECT_ID : sonic-shuttle-381413
  _VERSION : latest
  _IMAGE: us-central1-docker.pkg.dev/sonic-shuttle-381413/symfony/symfony-cicd
