#apiVersion: extensions/v1beta1
apiVersion: apiextensions.k8s.io/v1
kind: Ingress
metadata:
  name: www-domain
spec:
  rules:
    - host: www.example.com
      http:
        paths:
          - backend:
              serviceName: www
              servicePort: 80