#apiVersion: extensions/v1beta1
apiVersion: apiextensions.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: www-domain
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /www
            backend:
              serviceName: www
              servicePort: 80