version: '3.8'

services:
  zookeeper:
    container_name: kafka-multiple-zookeeper
    build:
      context: ZooKeeper
    ports:
      - '2181:2181'
    networks:
      kafkanet:
        ipv4_address: 10.6.0.2

  kafka-1:
    container_name: kafka-server-1
    build:
      context: server
      target: server
    command:
      - --override
      - broker.id=1
      - --override
      - zookeeper.connect=10.6.0.2:2181
    depends_on:
      - zookeeper
    networks:
      kafkanet:
        ipv4_address: 10.6.0.3

  kafka-2:
    container_name: kafka-server-2
    build:
      context: server
      target: server
    command:
      - --override
      - broker.id=2
      - --override
      - zookeeper.connect=10.6.0.2:2181
    depends_on:
      - zookeeper
    networks:
      kafkanet:
        ipv4_address: 10.6.0.4

  kafka-3:
    container_name: kafka-server-3
    build:
      context: server
      target: server
    command:
      - --override
      - broker.id=3
      - --override
      - zookeeper.connect=10.6.0.2:2181
    depends_on:
      - zookeeper
    networks:
      kafkanet:
        ipv4_address: 10.6.0.5

  kafka-connect:
    container_name: kafka-connect
    tty: true
    volumes:
      - './server/kafka-connect:/opt/kafka/connect'
    build:
      context: server
      target: connect
    depends_on:
      - zookeeper
      - kafka-1
      - kafka-2
      - kafka-3
    networks:
      kafkanet:
        ipv4_address: 10.6.0.6

networks:
  kafkanet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16
          gateway: 10.6.0.1
