apiVersion: v1
kind: Pod
metadata:
  name: proxy
spec:
  containers:
    - name: proxy
      image: nginx:1.12.2
      volumeMount:
        - name: tls
          mountPath: /etc/ssl/certs/
  volumes:
    - name: tls
      secret:
        secretName: domain-pki
### PreDeploy ###
# openssl req -newKey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out cert.pem
# kubectl create secrets tls domain-pki --cert cert.pem --key key.pem

### PostDeploy ###
# kubectl exec -ti proxy -- sh
# ls /etc/ssl/certs/