apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: image_name
      image: private_image
  imagePullSecrets:
    - name: docker-registry

### PreDeploy ###
# kubectl create secret docker-registry registry-creds \
#  --docker-server=SERVER --docker-username=USER --docker-password=PWD --docker-email=EMAIL
