apiVersion: v1
kind: Pod
metadata:
  name: pod-default
spec:
  containers:
    - name: alpine
      image: alpine:3.15
      command:
        - "sleep"
        - "10000"
# token path : /run/secrets/kubernetes.io/serviceaccount/token

### Post Pod creation ###
# apk add --update curl
# TOKEN=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
# curl -H "Authorization: Bearer $TOKEN" https://kubernetes/api/v1/ --insecure