apiVersion: v1
kind: Pod
metadata:
  name: www-2
spec:
  containers:
    - name: www
      image: nginx:1.18-alpine
      resources:
        limits:
          memory: 120M
        requests:
          memory: 100M
