apiVersion: v1
kind: Pod
metadata:
  name: www-3
spec:
  containers:
    - name: www
      image: nginx:1.18-alpine
      resources:
        limits:
          memory: 512M
        requests:
          memory: 64M
