apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2022-07-06T07:31:54Z"
  generation: 2
  labels:
    app: symfony-nginx-ci-cd-gke
  name: symfony-nginx-ci-cd-gke
  namespace: default
  resourceVersion: "324997"
  uid: 64a09c43-8118-4dfe-b0a4-278ce74dfd8b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: symfony-nginx-ci-cd-gke
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: symfony-nginx-ci-cd-gke
    spec:
      containers:
        - image: nginx:latest
          imagePullPolicy: Always
          name: nginx-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: gcr.io/gcp-devops-354514/symfony-ci-cd:latest
          imagePullPolicy: IfNotPresent
          name: symfony-ci-cd-sha256-2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2022-07-06T07:32:02Z"
      lastUpdateTime: "2022-07-06T07:32:02Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-07-06T07:31:54Z"
      lastUpdateTime: "2022-07-06T08:09:01Z"
      message: ReplicaSet "symfony-nginx-ci-cd-gke-798c4dbdf6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3