apiVersion: v1
kind: Pod
metadata:
  name: wp
spec:
  containers:
    - name: wordpress
      image: wordpress:4.9-apache
      env:
        - name: WORDPRESS_DB_PASSWORD
          value: mysqlpwd
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysqlpwd
      volumeMounts:
        - name: mysql_data
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql_data
      emptyDir: {}