apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
    - name: alpine
      image: alpine
      command:
        - sleep
        - 10000
      volumeMounts:
        - name: creds
          mountPath: /etc/creds
          readOnly: true
  volumes:
    - name: creds
      secret:
        secretName: service-creds
        items:
          - key: username.txt
            path: service/user
          - key: password.txt
            path: service/pass

### PreDeploy ###
# kubectl create secret generic service-creds --from-file=./username.txt --from-file=password.txt

### PostDeploy ###
# kubectl exec -ti alpine -- sh
# cat /etc/creds/service/user
# cat /etc/creds/service/pass