apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
        - name: nginx
          image: nginx:1.14-alpine
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
          # necessary to redeploy when config map was updated
          # create env var hash
          # export CONFIG_HASH=$(kubectl get cm -o yaml | sha256sum | cut -d' ' -f1)
          # update deploy config hash and apply the deployment
          # envsubst '${CONFIG_HASH}' < deploy.yaml | kubectl apply -f -
          env:
            - name: CONFIG_HASH
              value: ${CONFIG_HASH}
      volumes:
        - name: config
          configMap:
            name: www-config
