apiVersion: v1
kind: Pod
metadata:
  name: api-env
spec:
  containers:
    - name: api
      image: lucj/messages:1.0
      env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: mongoURL