apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.zalando.org
spec:
  group: zalando.org
  scope: Namespaced
  names:
    kind: Database
    plural: databases
    singular: database
    shortNames:
      - db
      - dbs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
