name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google cloud setup
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          # service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          cleanup_credentials: true

      - name: Setup Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Use gcloud CLI
        run: gcloud info

      #- name: Configure docker authentication
      #  run: gcloud auth configure-docker gcr.io -q

      #- name: Build the Docker image
      #  run: docker build -t ${{ secrets.GCR_IMAGE }} .

      #- name: Push the Docker image
      #  run: docker push ${{ secrets.GCR_IMAGE }}
