name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY}}

      - name: Build the Docker image
        run: docker build -t ${{ GCR_IMAGE }} .

      - name: Build the Docker image
        run: docker push ${{ GCR_IMAGE }}
