name: Docker Image CI

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

env:
  REPOSITORY: yosribahri
  IMAGE: symfony

jobs:

  setup-build-publish:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --target=dev -t $REPOSITORY/$IMAGE:${GITHUB_SHA}

      #- name: Unit tests
      #  run: docker run -ti $REPOSITORY/$IMAGE:${GITHUB_SHA} vendor/bin/phpunit

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image
        run: docker push $REPOSITORY/$IMAGE:${GITHUB_SHA}
