name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: 'actions/checkout@v3'

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      # @see https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
      - id: 'auth'
        name: Authenticate with Google Cloud Platform
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          token_format: 'access_token'

      - name: Login to Google Artifact Registry
        uses: 'docker/login-action@v2'
        with:
          registry: https://${{ secrets.GOOGLE_CONTAINER_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push docker image
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          target: dev
          tags: |
            ${{ secrets.GOOGLE_CONTAINER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/symfony/symfony-cicd:${{ github.sha }}
            ${{ secrets.GOOGLE_CONTAINER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/symfony/symfony-cicd:dev
          #build-args: |
          #  BUILD_DATE=date
