name: Docker Image CI

on:
  push:
    branches:
      - google-auth

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: Google cloud setup
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Docker login
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ secrets.GOOGLE_CONTAINER_REGISTRY }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build docker image
        run:  docker build . -t ${{ secrets.GOOGLE_CONTAINER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/symfony-ci-cd

      - name: Push docker image to GCR
        run:  docker push ${{ secrets.GOOGLE_CONTAINER_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/symfony-ci-cd

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SSH_SERVICE_ACCOUNT_KEY }}'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - id: 'compute-ssh'
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'symfony-ci-cd-vm2'
          zone: 'us-central1-c'
          ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
          command: 'echo Hello world'
